# Generated by Django 5.1.4 on 2025-01-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.UUIDField()),
                ('equipment_type', models.CharField(choices=[('tractor', 'Трактор'), ('combine', 'Комбайн'), ('plow', 'Плуг'), ('seeder', 'Сеялка'), ('sprayer', 'Опрыскиватель'), ('harvester', 'Уборочная машина'), ('mower', 'Косилка'), ('baler', 'Пресс-подборщик'), ('cultivator', 'Культиватор'), ('fertilizer_spreader', 'Разбрасыватель удобрений')], max_length=50)),
                ('service_type', models.CharField(choices=[('harvest_wheat', 'Сбор пшеницы'), ('harvest_corn', 'Сбор кукурузы'), ('harvest_potatoes', 'Сбор картофеля'), ('harvest_sunflower', 'Сбор подсолнечника'), ('harvest_rice', 'Сбор риса'), ('harvest_beets', 'Сбор свёклы'), ('plowing', 'Вспашка'), ('seeding', 'Посев'), ('spraying', 'Опрыскивание'), ('fertilizing', 'Внесение удобрений'), ('mowing', 'Косилка'), ('baling', 'Скирдообразование'), ('cultivating', 'Культивация'), ('soil_compaction', 'Уплотнение почвы'), ('field_rolling', 'Каткование поля'), ('weeding', 'Прополка'), ('irrigation', 'Орошение'), ('transport_grain', 'Транспортировка зерна'), ('transport_hay', 'Транспортировка сена'), ('transport_fertilizers', 'Транспортировка удобрений'), ('load_unload', 'Погрузка/разгрузка'), ('mulching', 'Мульчирование')], max_length=50)),
                ('availability_status', models.BooleanField(default=True)),
                ('price_per_hectar', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
